apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cd-s-services-base-usce1-delivery-node
serialPipeline:
  stages:
  - targetId: gke-stage-delivery
    profiles: []
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
              service: "push-delivery-node-service"
              deployment: "push-delivery-node"
        canaryDeployment:
          percentages: [50]
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: gke-stage-delivery
description: GKE cluster
gke:
 cluster: projects/push-stage-apps/locations/us-central1/clusters/gke-s-services-base-usce1
