steps:
# Step 1: Build the Docker Image and push to Artifact Registry
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - | 
      #!/bin/bash
      touch key.p8
      cp .env.sample .env
      gcloud builds submit --region=us-central1 --tag us-central1-docker.pkg.dev/push-stage-apps/ar-s-services-base-usce1/push-delivery-node-image:$SHORT_SHA
      
options:
 logging: CLOUD_LOGGING_ONLY  
