apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-delivery-node
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-delivery-node
  template:
    metadata:
      labels:
        app: push-delivery-node
    spec:
      containers:
      - name: push-delivery-node
        image: "us-central1-docker.pkg.dev/push-stage-apps/ar-s-services-base-usce1/"
        ports:
        - containerPort: 7575
      env:
        - name: DELIVERY_NODES_NET
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODES_NET
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: REDIS_URL
        - name: DELIVERY_NODE_DB_HOST
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODE_DB_HOST
        - name: DELIVERY_NODE_DB_NAME
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODE_DB_NAME
        - name: DELIVERY_NODE_DB_USER
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODE_DB_USER
        - name: DELIVERY_NODE_DB_PASS
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODE_DB_PASS
        - name: DELIVERY_NODE_APN_KEY_ID
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODE_APN_KEY_ID
        - name: DELIVERY_NODE_APN_TEAM_ID
          valueFrom:
            secretKeyRef:
              name: delivery-apps-secret
              key: DELIVERY_NODE_APN_TEAM_ID
      serviceAccountName: sa-apps
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: push-delivery-node-service
  spec:
    type: LoadBalancer
    selector:
      app: push-delivery-node
    ports:
    - port: 7575
      targetPort: 7575
